PCRE2Project/pcre2

README

Probably might be better to collect more of these into a bigger update, but the update to the google group seems more important, so posting this anyway

doc: mostly wording issues, but more importantly a fixed group link

---

Makefile.am

needed for `make dist` to work

build: update filelist after JIT update

---

build.zig

maintaining build.zig to latest zig compiler updates

update to latest zig

---

src/pcre2posix.h

This is a regression from PCRE1 `<pcreposix.h>`.

Add idempotent guards to pcre2posix.h

---

Makefile.am
doc/pcre2jit.3

While at it, make sure the list of files by sljit is updated after last import.

jit: add LoongArch support

---

src/pcre2_jit_simd_inc.h

This patch enables SIMD support on LoongArch platform, already tested on real hardware and qemu.

jit: Add LoongArch SX 128 bit SIMD Support.

---

.github/workflows/build.yml
.github/workflows/dev.yml
src/pcre2_jit_simd_inc.h

Run a build with debugging enabled, link-size of 4 and sanitizers.

ci: add dev build to serve as canary

---

build.zig

Adds static linking, better handling of copied files, and support latest Zig compiler.

Improve Zig build & support latest Zig

---

configure.ac

The test is now done in sljitConfigCPU.h

Fix autoconf test for --enable-jit=auto

---

CMakeLists.txt
HACKING
config-cmake.h.in
configure.ac
src/config.h.generic
src/config.h.in
src/pcre2.h.generic
src/pcre2.h.in
src/pcre2_auto_possess.c
src/pcre2_compile.c
src/pcre2_convert.c
src/pcre2_match.c
src/pcre2_study.c
src/pcre2grep.c
src/pcre2test.c
vms/configure.com

I don't recommend squashing this PR into a single commit; it has been deliberately submitted as a series of three independent commits.
Looking forward to comments.

Add assertion macros, use new PCRE2_UNREACHABLE assertion at unreachable points in code

---

NON-AUTOTOOLS-BUILD
README
configure.ac
src/config.h.generic
src/pcre2.h.generic

Reflect the new location of sljit and update release files

autotools: fix --enable-jit=auto

---

src/pcre2_internal.h
src/pcre2_printint.c
testdata/testinput2
testdata/testoutput2
testdata/testoutput8-16-2
testdata/testoutput8-16-3
testdata/testoutput8-16-4
testdata/testoutput8-32-2
testdata/testoutput8-32-3
testdata/testoutput8-32-4
testdata/testoutput8-8-2
testdata/testoutput8-8-3
testdata/testoutput8-8-4

Rename cond ref to capture ref

---

CMakeLists.txt
Makefile.am
PrepareRelease
README
configure.ac
m4/pcre2_visibility.m4
src/pcre2.h.generic
src/pcre2.h.in
src/pcre2_compile.c
src/pcre2_convert.c
src/pcre2_internal.h
src/pcre2_util.h
src/pcre2grep.c

Fix a build failure in AIX and prevent warnings in Windows.

build: improve portability of assertions

---

src/pcre2_compile.c
src/pcre2_compile.h
src/pcre2_compile_class.c
testdata/testinput12
testdata/testinput5
testdata/testoutput12-16
testdata/testoutput12-32
testdata/testoutput5

I totally forgot about the 'r' flag. I am sorry.

Fix case restricted range processing

---

src/pcre2_jit_compile.c

Something less important, but I wanted to do eventually. Depends on #566

Improve xclass range list matching

---

.github/workflows/codeql.yml

Update CodeQL to v3

---

src/pcre2_jit_compile.c
src/pcre2_jit_test.c

Another patch to reduce char1 compilations, which can be quite large for xclasses/eclasses.

Improve repeat support for plus

---

src/pcre2_jit_compile.c

Another patch which removes generated code duplications for xclass/eclass-es. Contains source code indentation changes.

Rework limited range repeats

---

src/pcre2_jit_char_inc.h
src/pcre2_jit_test.c

Fix xclass compilation

---

RunTest
RunTest.bat
doc/html/pcre2_set_substitute_case_callout.html
doc/html/pcre2api.html
doc/html/pcre2test.html
doc/pcre2.txt
doc/pcre2_set_substitute_case_callout.3
doc/pcre2api.3
doc/pcre2test.1
doc/pcre2test.txt
src/pcre2.h.generic
src/pcre2.h.in
src/pcre2_context.c
src/pcre2_error.c
src/pcre2_intmodedep.h
src/pcre2_substitute.c
src/pcre2test.c
testdata/testinput2
testdata/testoutput2

Completely redo the substitute-case-callout work

---

doc/html/pcre2.html
doc/html/pcre2api.html
doc/html/pcre2build.html
doc/pcre2.3
doc/pcre2.txt
doc/pcre2api.3
doc/pcre2build.3

Fix two typos in pcre2api, plus some other minor issues

---

src/pcre2_compile_cgroup.c
testdata/testinput2
testdata/testoutput2

It looks like I am bad at copying code.

Fix heapsort in capture list construction

---

src/pcre2_substitute.c
src/pcre2test.c
testdata/testoutput10
testdata/testoutput2
testdata/testoutput5
testdata/testoutput9

Add matching error-offset output to pcre2test for substitute

---

doc/html/pcre2api.html
doc/pcre2.txt
doc/pcre2api.3

Fix documentation typo
