PCRE2Project/pcre2

doc/html/pcre2convert.html
doc/pcre2convert.3

I noticed a minor mistake in the docs, here's the fix.

Fix option name in pcre2convert docs

---

src/pcre2grep.c

When BSD's fseek moves the position of a read stream within the
current buffer space, will avoid calling lseek for performance reasons, and therefore will
not update that position in the corresponding file handle, breaking the current implementation for -m (that supports stdin as a shared file)
There is ongoing discussion with NetBSD to change that, but the code has been around this way for decades and is likely to affect other UNIX (ex: AIX has been confirmed affected), so it is better to avoid that.
Fixes: #10

pcre2grep: workaround a common optimization in BSD fseek(stdin)

---

RunTest
src/pcre2test.c

If `pcre2test -S` is not supported then avoid checking for it
in a test.
There is already a conditional check for it to be used when it is
needed and it is available, so adjust that as well.
While at it, update the list of platforms that don't support it.

test: avoid failing RunTest if pcre2test -S is not supported

---

doc/pcre2_jit_stack_create.3
src/pcre2_jit_misc.c

An integer overflow that is slightly more relevant in the old PCRE codebase (where it will lead to Undefined Behaviour and if able to be triggered correctly a bug that might have security implications), but still worth addressing explicitly in the new codebase IMHO.
Avoid the overflow by checking and failing the value early, and
while at it make the check clearer and document the failure mode.

jit: avoid wraparound in stack size

---

CMakeLists.txt
configure.ac

Since d5a61ee8 (Patch to detect (and ignore) symlink loops in
pcre2grep., 2021-08-28), there is optional code that depends
on readlink and PATH_MAX but that had only detection added for
the first.
GNU Hurd doesn't have the later so it fails to build.
Improve the detection to include both dependencies in autotools
and cmake to fix that.
Signed-off-by: Carlo Marcelo Arenas Belón <carenas@gmail.com>

pcre2grep: fix build for Hurd

---

doc/html/pcre2_set_compile_extra_options.html
doc/html/pcre2_substitute.html
doc/html/pcre2pattern.html
doc/pcre2_set_compile_extra_options.3
doc/pcre2_substitute.3
doc/pcre2api.3
doc/pcre2pattern.3
doc/pcre2test.1
src/pcre2_intmodedep.h
src/pcre2_jit_compile.c
src/pcre2_jit_match.c
src/pcre2_jit_test.c
src/pcre2grep.c
testdata/testinput7
testdata/testoutput7

First patch is a bugfix to strangely aligned documentation and an unfortunate typo.
Second patch is a little more involved, as I tried to align the pcre2_substitute documentation so it will be clearly readable in both html and troff versions
Last patch is not related to this topic, but long overdue

doc: formatting/typo fixes to documentation

---

CMakeLists.txt

Issue can be replicated, regardless of OS or generator used.
Affected code doesn't seem to be very useful or needed, and has been tested to work with modern MSVC and Xcode

cmake: avoid man3 glob post processing

---

doc/pcre2api.3
src/pcre2_dfa_match.c
src/pcre2_match.c
src/pcre2_substitute.c

Probably not that critical, as it has been there since the very beginning but seems like a better behaviour to have when using PCRE2_ZERO_TERMINATED and matches better the documentation.
Problem also exist in pcre2_dfa_match and POSIX (but there crashing is the expected behaviour), as well as in pcre2_substitute where it could crash even when not using PCRE2_ZERO_TERMINATED, so split onto multiple patches for easy of reviewing.
pcre2_substitute needs a lot more checks and will have to keep an exception as the replacement string was not checked before and it just happens to work fine regardless when the length was given as 0.
Tests are still missing and I am not sure of the design required to implement them yet, but if that is deemed not critical (after all that is the current state, as …

match: avoid crash if subject NULL and PCRE2_ZERO_TERMINATED

---

RunGrepTest

Notably, running the script directly from a build subdirectory will infer srcdir as .. if not otherwise set, but doesn't work for these. With this commit sh pcre2_grep_test.sh works as expected.

RunGrepTest: Fix tests 132 and 133 when srcdir is relative

---

src/pcre2_intmodedep.h
src/pcre2_match.c

On CHERI, and thus Arm's Morello prototype, pointers are represented as
hardware capabilities, which consist of both an integer address and
additional metadata, meaning they are twice the size of the platform's
size_t type, i.e. 16 bytes on a 64-bit system. The ovector member of
heapframe happens to only be 8 byte aligned, and so computing frame_size
ends up with a multiple of 8 but not 16. Whilst the first frame is
always suitably aligned, this then misaligns the frame that follows it,
resulting in an alignment fault when storing a pointer to Fecode at the
start of match.
Thus, round up frame_size to a multiple of heapframe's alignment to
ensure alignment is preserved. This can be completely optimised away on
traditional architectures and, since CHERI's capabilities are in fact
2 * …

match: Properly align heapframes for CHERI/Arm's Morello prototype

---

src/pcre2_jit_misc.c

eb42305f (jit: avoid integer wraparound in stack size definition (#42),
2021-11-19) introduces a check to avoid an integer overflow when
allocating stack size for JIT.
Unfortunately the maximum value was using PCRE2_SIZE_MAX, eventhough
the variable is of type size_t, so correct it.
Practically; the issue shouldn't affect the most common configurations
where both values are the same, and it will be unlikely that there would
be a configuration where PCRE2_SIZE_MAX > SIZE_MAX, hence the mistake
is unlikely to have reintroduced the original bug and this change should
be therefore mostly equivalent.
Signed-off-by: Carlo Marcelo Arenas Belón <carenas@gmail.com>

jit: use correct type when checking for max stack value

---

doc/html/pcre2build.html
doc/pcre2.txt
doc/pcre2build.3

Noticed while reading pcre2.txt. Apologies if this is the wrong way to update docs.

Fix typo `with-match-limit_depth` -> `with-match-limit-depth`

---

src/pcre2_fuzzsupport.c

This PR enables fuzzing of the JIT engine when PCRE2 is compiled with `--enable-fuzz-support --enable-jit`. 
I have tested this patch locally and it found some crashes in the JIT compiler (fixed in 50a51cb7e67268e6ad417eb07c9de9bfea5cc55a and 4ca0530b9bdf00d2485d612ddfab8d21c72dc83a).

Enable fuzzing of the JIT engine

---

.github/workflows/build.yml

Let's inaugurate the pull requests 🙂 
Here's a suggestion: you may use GitHub Actions for continuous integration. If you merge this, each time you push or receive a pull request, GitHub will build and test the code, then report success or failure with a ✔️ or ❌ sign on the commit or PR.
I wrote a very basic workflow (see the YAML file, it is pretty self-explanatory), but you may expand this to include more config options or combinations of options.
You can also see an [example of a run in my fork](https://github.com/ltrzesniewski/pcre2/runs/3644688236?check_suite_focus=true), or consult the [documentation](https://docs.github.com/en/actions).

Add a GitHub Actions build workflow

---

.github/workflows/build.yml
RunTest.bat

Configure and build (using cmake with Visual Studio) in Windows and validate no regressions are introduced by running some of the tests

ci: windows support

---

doc/pcre2_serialize_decode.3
doc/pcre2serialize.3

5438fc8a (Add serialization functions and tests with updated pcre2test.
Fix PCRE2_INFO_SIZE issues., 2015-01-23) introduced the typo.
Reported-by: @sjshuck
Fixes: #106

doc: avoid nonexistent PCRE2_ERROR_MEMORY error

---

.github/workflows/codeql.yml
.github/workflows/scorecards.yml

Scorecards is an [`Open Source Security Fundation`](https://openssf.org/) porject.
> Scorecards is an automated tool that assesses a number of important heuristics [("checks")](https://github.com/ossf/scorecard#scorecard-checks) associated with software security and assigns each check a score of 0-10. You can use these scores to understand specific areas to improve in order to strengthen the security posture of your project.
https://github.com/ossf/scorecard
In order to make Scorecards works correctly,  a `Read-only Access Token` needs to be added to the project.
You can reference https://github.com/ossf/scorecard-action#authentication

Add OpenSSF Scorecards to impove the security posture

---

src/pcre2_jit_compile.c

This continues the discussion from #105.
When compiled on x86, MSVC generates the following warning (which becomes an error when the _Treat Warnings As Errors_ option is used):
> pcre2_jit_compile.c(5889,40): warning C4018: '>=': signed/unsigned mismatch
on the following line:
https://github.com/PCRE2Project/pcre2/blob/b52d055d1b8feb6e56804c2062de65d50a5601e2/src/pcre2_jit_compile.c#L5889
This warning seems wrong at first, as `a_pri` and `b_pri` are of type `PCRE2_UCHAR`, while `max_pri` is of type `sljit_u32`, so both operands are supposed to be unsigned.
Turns out, [implicit conversion rules](https://en.cppreference.com/w/c/language/conversion) in C are... complicated. The way I understand them, the `a_pri + b_pri` expression is promoted to type `int`, which causes the signed/unsigned …

Fix integer promotion causing a warning in MSVC

---

CMakeLists.txt

This resolves an error that the listed .pdb files won't exist and make install fails
if 8, 16 and 32 bit libraries weren't all built.
Signed-off-by: William A Rowe Jr <wrowe@vmware.com>

Include specific .pdb files only for chosen char size libs when shared

---

NON-AUTOTOOLS-BUILD

This seems needed following https://github.com/PCRE2Project/pcre2/commit/4514ddd2a2a002214caf46c05326af3c1fe302af.

Add `pcre2_ucptables.c` to non-autotools build docs

---

src/pcre2_jit_compile.c

If `pcre2_jit_compiler` is called simultaneously for the first time from 2 (or more) threads, then one of the calls may fail with the `PCRE2_ERROR_NOMEMORY` error.

Fixed race condition that occurs when initializing the executable_allocator_is_working variable in the pcre2_jit_compile function

---

.bazelrc
.gitignore
BUILD.bazel
MODULE.bazel
WORKSPACE.bazel

I mainly use [bazel](https://bazel.build/) as my build system and I was wondering if pcre2 would be willing to accept these files upstream to add pcre2 to the [bazel central registry](https://github.com/bazelbuild/bazel-central-registry). I _can_ write patches for the repository and submit it that way, but it is preferred to have them in the repository.
At the moment this is a minimal configuration that successfully runs the `pcre2demo`. e.g.
```sh
bazel run //:pcre2demo -- -g "\\w+" "hello world"
```
```
Match succeeded at offset 0
0: hello
No named substrings
Match succeeded again at offset 6
0: world
No named substrings
```
If this was accepted and submited to the bazel central registry then bazel users would only have to add the following to their `MODULE.bazel`.
```python …
```

Bazel and bazel central registry support

---

src/pcre2.h.generic
src/pcre2.h.in
src/pcre2posix.h

4 functions prototypes were missing PCRE2_CALL_CONVENTION in src/pcre2posix.h
All functions prototypes returning pointers had out of place PCRE2_CALL_CONVENTION in src/pcre2.h.*
These produced errors when building for Windows with #define PCRE2_CALL_CONVENTION __stdcall.
Tests after changes (Debug and Release configs): All OK.

Missing/misplaced PCRE2_CALL_CONVENTION macros in functions prototypes

---

CMakeLists.txt

`cmake_minimum_required()` must be the first instruction of a top CMakeLists, otherwise side effects may occur.

CMake: move `cmake_minimum_required()` before `project()`

---

configure.ac
src/config.h.in

* required to support 64-bit filesystems (inodes) on 32-bit platforms: https://flameeyes.blog/2010/12/15/another-good-reason-to-use-64-bit-installations-large-file-support-headaches/
Bug: https://bugs.gentoo.org/878475

Enable LFS on 32-bit platforms

---

src/pcre2_compile.c

When using Clang-11 on Ubuntu 18+ we get these warnings:
```
pcre2_compile.c:3306:27: warning: variable 'min_repeat' may be uninitialized when 
used here [-Wconditional-uninitialized]
pcre2_compile.c:2690:22: note: initialize the variable 'min_repeat' to silence this warning
pcre2_compile.c:3307:27: warning: variable 'max_repeat' may be uninitialized when 
used here [-Wconditional-uninitialized]
pcre2_compile.c:2690:34: note: initialize the variable 'max_repeat' to silence this warning
```

Silence warnings about uninitialized min/max_repeat variables.

---

.github/workflows/cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which pcre2 already runs.
CIFuzz can help detect catch regressions before they are merged in, catch fuzzing build issues, and has a variety of features (see the URL above). In the current PR the fuzzer is built on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>

ci: add CIFuzz action

---

.github/workflows/build.yml

Workaround for Windows builds 20221120.1[1]
Regardless of cmake version there is no point pulling any extra libraries
[1] https://github.com/actions/runner-images/issues/6627

ci: avoid pulling 64bit libraries from strawberry perl

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/scorecards.yml
src/pcre2_jit_compile.c

mostly to silence warnings in Visual Studio, but also making the code more consistent.

jit: replace open coded SSIZE_OF(sw)

---

src/pcre2_jit_misc.c

sljit allows building without an internal allocator, but instead using an external one.
make sure to only invoke the corresponding sljit call if an internal allocator is in use (the default and as coded in pcre integration) to avoid problems if the code is changed to use an external allocator instead.

jit: fix pcre2_jit_free_unused_memory() if sljit not using allocator

---

src/pcre2_jit_neon_inc.h
src/pcre2_jit_simd_inc.h

Resulting in a constant false result in aarch64 when using SIMD

jit: correctly implement utf_continue() for utf16

---

RunGrepTest

test: avoid double $srcdir references in RunGrepTest

---

.github/workflows/build.yml

using cmake (not recommended) so a naive way to make an universal build could be achieved, and which has the main purpose of building the arm64 code to catch any issues there as early as possible.

ci: add macOS universal build

---

src/pcre2test.c

on a side note; do we really need to test with 64MB of stack nowadays? if I recall correctly the limit might had been increased because of some platforms that couldn't run without it (maybe Linux/m68k) but that was before 10.30 where the possibility of stack overflows was more likely.
AFAIK macOS uses 8M by default and was failing the -S call because the maximum allowed is a little less than 64M and therefore has been running fine with only that much (even before the latest improvements in 10.41)
if anything, and considering the trend to have multiple threads I would expect we should be instead looking at restricting the stack size (less than 1MB per thread stack size is IMHO common).

pcre2test: print max stack size in the right units

---

RunGrepTest

ironically, the old Solaris shell prints an error when setting an invalid environment variable to stdout and AFTER it fails to validate, therefore making it impossible to numb.
using `env` is cleaner and more portable anyway

test: avoid shell issues with Solaris 10

---

src/pcre2_valid_utf.c

A minor issue in the function to validate UTF which was already partially addressed with e8cdae3 (Correct an incorrect cast., 2017-04-14).

avoid truncation of error offset in valid_utf() when subject larger than INT_MAX

---

ChangeLog
Makefile.am
doc/html/pcre2_get_match_data_heapframes_size.html
doc/html/pcre2test.html
doc/pcre2_get_match_data_heapframes_size.3
doc/pcre2_match_data_free.3
doc/pcre2test.1
src/pcre2.h.in
src/pcre2_match_data.c
src/pcre2test.c

The proposed code, allows for an external application to implement logic similar to:
```
PCRE2 version 10.42 2022-12-11
re> /\[(a)]{1000}/expand,framesize
Frame size for pcre2_match(): 16128
data> \[a]{1000}\=ovector=1
Matched, but too many substrings
0: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
data> 
re> /a/memory,heapframes_size
Memory allocation (code space): 9
Heapframes size for pcre2_match(): 20643840
data> a\=ovector=0
0: a
data> 
re> /a/heapframes_size
Heapframes size for pcre2_match(): 20480
```
So that the system could recover from memory pressure in cases were match_data …

add pcre2_get_match_data_heapframes_size()

---

src/pcre2test.c

Tested in Linux, macOS, Windows and even NetBSD armv7 (that uses CLOCKS_PER_SEC == 100) and new code is even smaller.
CLOCKS_PER_SEC == 1000000 is mandated by C89 / POSIX so I would expect no portability issues

pcre2test: use microseconds instead of milliseconds for timing

---

CMakeLists.txt
configure.ac

Fixes to bootstrapping with older tools that would result in broken builds.
The `configure.ac` uses additional syntax to keep using the original macro that is used in bootstrapping for releases and that works fine even with really old gcc (would test and try to enable up to C11) and could be dropped once the  `AC_PREREQ` is updated as originally intended.

build: make the C99 requirement explicit

---

doc/html/pcre2_general_context_create.html
doc/html/pcre2_jit_stack_create.html
doc/html/pcre2_set_recursion_memory_management.html
doc/html/pcre2api.html
doc/pcre2_general_context_create.3
doc/pcre2_jit_stack_create.3
doc/pcre2_set_recursion_memory_management.3
doc/pcre2api.3
src/pcre2.h.generic
src/pcre2.h.in
src/pcre2_intmodedep.h
src/pcre2test.c

It doesn't change much in practice, but helps clarify the interfaces of some functions that were either documented with the wrong type or had mismatching types between declaration and implementation.

make sure to use either size_t or PCRE2_SIZE correctly

---

BUILD.bazel
CMakeLists.txt
Makefile.am
config-cmake.h.in
configure.ac
src/config.h.generic
src/config.h.in
src/pcre2_chkdint.c
src/pcre2_compile.c
src/pcre2_internal.h
src/pcre2test.c

A combined approach that addresses #196 and replaces #177
Unlike the original It allows in both cases to handle larger sizes than INT_MAX when possible

add a C23 inspired checked integer multiplication helper

---

.gitignore
build.zig

Hello.
[Zig](https://ziglang.org) is a general-purpose programming language and toolchain for maintaining robust, optimal and reusable software.
Zig can leverage C source code base and recently got support for package manager (master branch). So it would be easy to use pcre2 in Zig projects.
Build standalone library with:
```bash
zig build
```
Or use it in your project:
Specify dependency in manifest `build.zig.zon`:
```zig
.{
.name = "example",
.version = "0.0.0",
.dependencies = .{
.pcre2 = .{
.url = "https://github.com/PCRE2Project/pcre2/archive/fa35393d7935f7ef2833bf89d16d49a05c17923b.tar.gz",
.hash = "1220cd78969639ad750886231c71cdb991459792ac2187ad57552aab9df97a8ba98c",
},
},
}
```
Hash and commit will be different.
In `build.zig` link pcre2 to your executable.
```zig
const …
```

zig build support

---

doc/html/pcre2grep.html
doc/pcre2grep.1

using -E without -i doesn't make sense, but it could give confusing results otherwise

pcre2grep: documentation updates

---

CMakeLists.txt
configure.ac

Improve the checks introduced with 4678857 (add a C23 inspired checked integer multiplication helper (#198), 2023-02-03) and that could result in build failures at least in AIX with xlc

improve __buitin_mul_overflow() checks

---

NON-AUTOTOOLS-BUILD
doc/html/NON-AUTOTOOLS-BUILD.txt

This file is included by pcre2_tables.c, so it should not be built manually, otherwise it causes loads of errors like this:
```
pcre2-10.42/src/pcre2_ucptables.c:1517:3: warning: braces around scalar initializer
1517 |   { 3563, PT_SC, ucp_Unknown }
|   ^
pcre2-10.42/src/pcre2_ucptables.c:1517:3: note: (near initialization for ‘PRIV’)
pcre2-10.42/src/pcre2_ucptables.c:1517:5: error: invalid initializer
1517 |   { 3563, PT_SC, ucp_Unknown }
|     ^~~~
pcre2-10.42/src/pcre2_ucptables.c:1517:5: note: (near initialization for ‘PRIV’)
pcre2-10.42/src/pcre2_ucptables.c:1517:11: warning: excess elements in scalar initializer
1517 |   { 3563, PT_SC, ucp_Unknown }
|           ^~~~~
pcre2-10.42/src/pcre2_ucptables.c:1517:11: note: (near initialization for ‘PRIV’) …
```

Remove pcre2_ucptables.c from sources in build doc

---

ChangeLog
configure.ac
doc/pcre2test.1
src/pcre2.h.generic
src/pcre2test.c

Mainly to easily document differences of behaviour between different flavors of the library
```
PCRE2 version 10.43-DEV 2023-04-14 (8-bit)
re> /\x{df00}/
Failed: error 134 at offset 7: character code point value in \x{} or \o{} is too large
PCRE2 version 10.43-DEV 2023-04-14 (16-bit)
re> /\x{df00}/
data> 
```

pcre2test: print library bitwidth in banner for usability

---

.gitignore
src/pcre2test.c

This could result in a buffer over read as reported in the linked ticket and that was only possible after 10.34 when match_invalid_utf was introduced, or if invalid data was matched without UTF validation, which is known to have undefined behaviour.
Also makes utf82ord() save when used with invalid UTF, as the same issue could be triggered in other ways (ex: using aftertext) as shown by:
```
PCRE2 version 10.34 2019-11-21
re> /(?<=..)X/match_invalid_utf,aftertext
data> \xc3\xb1x{10ffff}X\xb1\xf4\x8f\xbf
```
Fixes: #235

pcre2test: avoid printing invalid utf trail in partial match

---

src/pcre2_match.c
testdata/testinput10
testdata/testinput12
testdata/testoutput10
testdata/testoutput12-16
testdata/testoutput12-32

Addresses the inconsistency raised by the failing tests in #237 as shown by:
```
PCRE2 version 10.34 2019-11-21
re> /.a/match_invalid_utf,allvector,jit
data> b\xb1\=ph,ovector=1
No match
0: <unchanged>
data> b\xb1\=ph,ovector=1,no_jit
Partial match: b\x{b1}
** ovector[1] is not equal to the subject length: 1 != 2
0: 0 1
```

no partial match if trailing data is invalid utf

---

src/pcre2grep.c

somehow it still produced red output, but was doing the wrong operations when the macro was called with expressions like `code - 30`

pcre2grep: correctly convert colors in Windows

---

testdata/testinput10
testdata/testinput2
testdata/testoutput10
testdata/testoutput2

"Add tests which use recurse to test \K and Mark in atomic scope" is used to override two branches of the init_frame function, as follows:
https://github.com/PCRE2Project/pcre2/blob/1bc34ffa64c33381d793fb5cdddf3f484e603d23/src/pcre2_jit_compile.c#L2188
https://github.com/PCRE2Project/pcre2/blob/1bc34ffa64c33381d793fb5cdddf3f484e603d23/src/pcre2_jit_compile.c#L2197
"Add the test which use firstline,utf,match_invalid_utf together" is used to overwrite a branch of do_utfreadnewline_invalid:
https://github.com/PCRE2Project/pcre2/blob/1bc34ffa64c33381d793fb5cdddf3f484e603d23/src/pcre2_jit_compile.c#L4657

Add some test cases

---

.gitignore

It is a common practice to create a build subdirectory and run cmake from there.

Ignore build subdirectory.

---

CMakeLists.txt

I am building PCRE2 using CMake, with the build tree separate from the source. When I run the test suite, I encounter the following failures:
```
$ make test
Running tests...
When testing is complete, review test output in the
"/home/skunk/.conan2/p/b/pcre245455d9ceb200/b/build/Testing/Temporary" folder.
Test project /home/skunk/.conan2/p/b/pcre245455d9ceb200/b/build
Start 1: pcre2_test
1/4 Test #1: pcre2_test .......................***Failed    0.01 sec
Start 2: pcre2_grep_test
2/4 Test #2: pcre2_grep_test ..................***Failed    0.01 sec
Start 3: pcre2_jit_test
3/4 Test #3: pcre2_jit_test ...................   Passed   12.55 sec
...
```
If I run the test scripts directly (in the build tree), I see the following:
```
$ sh ./pcre2_test.sh 
Cannot find the testdata directory
$ sh …
```

Fix tests in out-of-source-tree CMake builds

---

src/pcre2_jit_neon_inc.h
src/pcre2_jit_simd_inc.h

Do the minimal change required to address the underlying issue (not a hang, but very degraded performance, with the possibility of corruption that could result in an infinite loop by accidentally decrementing `str_ptr`) that was reported.
Fixes: #257

jit: add support for partial matches to arm64 simd helper

---

CMakeLists.txt

Since 3.27 was released, the following warning is being triggered:
CMake Deprecation Warning at CMakeLists.txt:108 (CMAKE_MINIMUM_REQUIRED):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
Update version and while at it, clean the code and make sure it errors out even when invoked with an ancient (<=2.4) version of cmake that would just warn otherwise.

cmake: increase minimum to 3.5

---

HACKING
src/pcre2_match.c

Since 1e78b77 (Code for variable-length lookbehinds, 2023-08-06) the Windows CI job (doing 32bit) is showing:
```
pcre2_match.c(5780,16): warning C4018: '>': signed/unsigned mismatch [pcre2-8-static.vcxproj]
pcre2_match.c(5781,16): warning C4018: '>': signed/unsigned mismatch [pcre2-8-static.vcxproj]
```
Restrict the ptrdiff to the valid range and while at it remove an unnecessary conditional from the UTF section an update related documentation as well.

match: avoid signed/unsigned mismatch

---

doc/pcre2pattern.3
src/pcre2_compile.c
testdata/testinput5
testdata/testoutput5

Avoid regressions by matching the observed behaviour of Javascript when the PCRE2_EXTENDED_ALT_BSUX option is in effect, and make sure to document the exception.

Spaces are not allowed within \u{} in BSUX mode

---

src/pcre2_match.c
testdata/testinput1
testdata/testoutput1

match: also restore originally unset entries in recursion

---

ChangeLog
doc/pcre2_set_compile_extra_options.3
doc/pcre2api.3
doc/pcre2pattern.3
src/pcre2_compile.c
testdata/testinput5
testdata/testoutput5

Just like in the case of [:digit:], and as suggested in [UTS#18](https://unicode.org/reports/tr18/#Compatibility_Properties)

Allow restricting [:xdigit:] to ASCII for POSIX compatibility

---

src/pcre2_dfa_match.c

Fix a potential integer overflow in DFA matching (issue #303)

fix a possible integer overflow in DFA matching

---

pcre2-config.in
src/pcre2posix.h

Update pcre2-config so it will use the new suggested options since #243

Prefer PCRE2POSIX_SHARED to PCRE2_STATIC for pcre2posix

---

CMakeLists.txt

Fix an edge case from #249 for a library that was installed by cmake but that is built against using a different method.

cmake: set PCRE2POSIX_CFLAG in pcre2-config and pkg-config

---

testdata/testinput17
testdata/testoutput17

Not a regression, as it seems to be included with the 10.40 release.
Resolves the following error when building with [UBSAN](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) in a recent compiler:
```
Test 17: JIT-specific features when JIT is available
src/pcre2_jit_match.c:124:25: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/pcre2_jit_match.c:124:25 in 
src/pcre2_jit_match.c:126:25: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/pcre2_jit_match.c:126:25 in 
```

test: avoid Undefined Behaviour because of NULL pointer arithmetic in test17

---

src/pcre2_maketables.c
testdata/testinput3
testdata/testoutput3
testdata/testoutput3A
testdata/testoutput3B

Fixes an issue observed at least in macOS, where the locale uses an UTF-8 charmap by default and at least toupper() uses an UTF-8 equivalent character for codepoint 181[1] and returns a higher than 255 result.
[1] https://en.wikipedia.org/wiki/Mu_(letter)

maketables: avoid misleading values in case flipping table

---

src/pcre2_jit_compile.c
testdata/testinput4
testdata/testoutput4

I have started working on vreverse. Unfortunately the task is very hard, because it adds another layer to the already complex bracket/assertion matching. Each new layer kind of duplicates the complexity, so I have no idea how many bugs I introduce with this patch. To tell the truth it was a long time ago when I developed the original code, and forgot many things since then.
The tests are passing now, although @PhilipHazel mentioned the vreverse tests are disabled for jit. I didn't see anything which disables them. Is there something I miss?
The patch also contains some unicode fixes, they can be moved to another patch if needed.

Implement vreverse in jit

---

src/pcre2_fuzzsupport.c

This PR makes two changes to the PCRE2 fuzzer. Namely, it uses part of the input to determine the selection of the options, allowing for a greater selection of options (historically, it was restricted to 256 combinations of options -- significantly lower than potential) and adds an extra step in which JIT matches are compared to non-JIT matches as a simple differential oracle allowing for the detection of JIT miscompilation or incorrectness in either implementation.
Caveats:
- These changes change the input shape of the fuzzer, now using the first 8 bytes of input to determine the options and the rest as arbitrary input. This means that the existing corpus will be less useful, but will likely be back at coverage saturation in very little time by Clusterfuzz.
- The crashes which occur as a …

Fuzzer improvements (JIT, option entropy)

---

src/pcre2_fuzzsupport.c

If JIT is not enabled, these variables are unused. This should fix it.

Cleanup unused variables in fuzzsupport

---

src/pcre2_fuzzsupport.c

This has an undesirable consequence of making the code a bit more difficult to read... Seemed the simplest solution.

More unused variable cleanup

---

src/pcre2_jit_compile.c
src/pcre2_jit_simd_inc.h
src/pcre2_jit_test.c

The downside is SSE4.1 is the minimum for simd support. I don't see much perf difference with AVX2, but maybe it is just my machine.

Add AVX2 simd support on x86

---

src/pcre2_jit_neon_inc.h

Technically a false positive, but it might be easier to prevent it by going at the source this way.
Fixes: #302

jit: disable ASAN for arm64 SIMD helper

---

src/pcre2posix.c
testdata/testoutput18

Address some incorrect return values from `pcre2_regerror()` depending on the version of `snprintf` that it uses internally.
Isolates the `snprintf` calls to minimize its impact and does an unnecessary runtime detection under the assumption that calls to this code aren't performance sensitive.
Doing a proper configure time detection has been punted for now, since there is already several other places where the possibility of using a broken `snprintf` has already workarounds, that will likely also need to be changed.

pcre2posix: avoid snprintf quirks in regerror

---

ChangeLog
HACKING
doc/pcre2posix.3
src/pcre2posix.c

This was originally meant as a "fixup" for the changes introduced in #333, but includes additional changes that are shown independently in case they need to be dropped, albet it includes a critical brown bag patch that fixes a crash on the original code.
- The first patch is mostly code that I somehow didn't include in my last push as intended.
- The second patch fixes a crash when `pcre2_regerror(.., .., NULL, 0)` or equivalent is used.
- The third patch is documentation updates that might be relevant in addition.
There is actually a fourth patch that actually tightens the issues raised about overlong buffers, but it is not included in this series but kept on its own [branch](https://github.com/carenas/pcre2/tree/noposixlfs), let me know if you would rather had everything squashed there …

pcre2posix: additional updates for recent changes

---

.github/workflows/build.yml
.github/workflows/dev.yml

Restricted to pull requests, as it is heavy (~20min), but could help identify early problems with the proposed changes.
While at it, update and improve performance on the regular jobs

ci: add manyconfig job

---

src/pcre2_compile.c
src/pcre2_convert.c
src/pcre2grep.c

This addresses some rare crash conditions where PCRE2_UCHAR is larger than unsigned char. Additionally, ensures that arguments to ctype functions are not sign-extended.

Sanity checks for ctype functions

---

README
doc/html/README.txt
doc/html/pcre2api.html
doc/html/pcre2build.html
doc/html/pcre2jit.html
doc/html/pcre2pattern.html
doc/html/pcre2posix.html
doc/html/pcre2serialize.html
doc/html/pcre2syntax.html
doc/pcre2.txt
doc/pcre2api.3
doc/pcre2build.3
doc/pcre2jit.3
doc/pcre2pattern.3
doc/pcre2posix.3
doc/pcre2serialize.3
doc/pcre2syntax.3

Most of these typos were found with the following command:
find doc -type f -exec aspell -c {} \;

Fix various typos in documentation

---

src/pcre2_compile.c

Without this change the table is placed in `.data` section of a binary which is marked as read-write and counts to memory usage because it needs to be stored in memory. If we mark the table as `const`, as it should be since it's not modified anywhere, compiler moves it to `.rdata` which is read only and is backed by binary so it doesn't have to be reside in the memory.
I know the memory difference is negligible, but constant data should be always placed in constant section.

Mark pso_list const

---

configure.ac
src/config.h.in
src/pcre2_fuzzsupport.c

Unfortunately, there was an unexpected blocker on https://github.com/google/oss-fuzz/pull/11195 -- differential fuzzing support finding aborts made the build unacceptable for OSS-Fuzz, as these issues appear quite quickly.
This PR fixes it by making differential fuzzing conditional, while keeping fuzzing enabled for JIT and for the interpreter.

Conditionally enable differential fuzzing

---

.github/workflows/dev.yml
maint/ManyConfigTests
maint/README
src/pcre2_jit_compile.c
src/pcre2_jit_misc.c
src/pcre2_jit_simd_inc.h
src/pcre2_jit_test.c

A similar job to the one that was added originally and that used `gcc`.
The "fix" for the "Undefined Behaviour while shifting framesize" is a little more involved that I would like, but done this way to keep mostly the same logic.

ci: add dev job using clang

---

build.zig

This is the only breaking change since the previous update
https://ziglang.org/documentation/0.12.0/std/#std.Build.Step.Compile.installHeader

update build.zig to support zig 0.12.0

---

ChangeLog
m4/pcre2_visibility.m4

FTBFS with at least xlc or Sun Studio compilers
Fixes: #392

m4/pcre2_visibility.m4: make sure PCRE2_EXPORT is always safe

---

Makefile.am

typo in cbff6bb (Install OpenVMS support files, 2024-04-16)

autotools: fix `make dist`

---

doc/pcre2_set_max_pattern_compiled_length.3
src/pcre2_compile.c
src/pcre2test.c
testdata/testoutput8-16-2
testdata/testoutput8-16-3
testdata/testoutput8-16-4
testdata/testoutput8-32-2
testdata/testoutput8-32-3
testdata/testoutput8-32-4
testdata/testoutput8-8-2
testdata/testoutput8-8-3
testdata/testoutput8-8-4

Since 05aafb2 (Implement pcre2_set_max_pattern_compiled_length() and set this limit in the fuzzer, 2024-04-24), the memory modifier has reported the full size of the allocated "code" returned by `pcre2_compile`.
Problem is that the size of the structure used to hold that in memory also depends on the platform ABI and even alignment by the compiler, and has been therefore fragile to compare.
Revert to reporting only the additional memory that `pcre2_compile()` will use for the compiled pattern (including any data tables) and make sure that the limit provided with `pcre2_set_max_pattern_compiled_length()` also avoid the internal struct overhead.
Fixes: #415

pcre2test: memory reports only compiled memory usage for code/data

---

.gitignore
build.zig

The cache director is now prefixed with a .[0]
Also, std.Build.LazyPath has changed, and now the recommended way to create one that is relative to the repo root is via std.Build.path().
[0]: https://ziglang.org/download/0.13.0/release-notes.html#codezig-cachecode-renamed-to-codezig-cachecode

update build.zig to support zig 0.13.0

---

configure.ac
m4/pcre2_visibility.m4

Tested with the latest version of SunPro and TinyCC. It would also allow for other clang proprietary derivatives.
As usual, would fall cleanly for the cases where there is no support for `-fvisibility`

m4/pcre2_visibility.m4: add basic support for non GCC compilers

---

src/pcre2_fuzzsupport.c

We're getting an ASAN leak detection error when SUPPORT_JIT is not enabled since 10.44. This is the obvious fix. Thanks!

Also free newwdata when SUPPORT_JIT is not enabled

---

src/pcre2_compile.c

Might address #423, but otherwise a good cleanup that shouldn't have any real impact whatsoever.

pcre2_compile: belt and suspenders for check_lookbehinds()

---

ChangeLog
RunGrepTest
doc/html/pcre2_set_max_pattern_compiled_length.html
doc/html/pcre2grep.html
doc/pcre2grep.1
src/config.h.in
src/pcre2grep.c
testdata/grepinputv
testdata/grepoutput

Historically, `pcre2grep` removes empty lines of the file provided with the `-f` option and trims trailing space characters on each line, this means (among other differences) that it is not possible to provide an empty pattern through it and the following inconsistency is observed (comparing against GNU/*NIX grep):
```
% echo "" > input && cp input pat
% grep -qf pat input; echo $?
0
% ggrep -qf pat input; echo $?
0
% pcre2grep -qf pat input; echo $?
1
% pcre2grep -q "" input; echo $?
0
```
This allows for the more consistent:
```
% pcre2grep --posix-pattern-file -qf pat input; echo $?
0
% pcre2grep --posix-pattern-file -q -e "" input; echo $?
0
```

pcre2grep: add --posix-pattern-file for compatibility with other grep

---

RunGrepTest
testdata/grepoutput

Fix `RunGrepTest` at least in OpenBSD, where the validation for a locale mostly concerns with the charmap.

test: use a fully spec locale name in RunGrepTest

---

src/pcre2test.c

Could trick pcre2test into trying to decode a trailing utf character from the subject  using data outside of what was read into its buffer.
Note that under normal circumstances the buffer is zero terminated and so any over read will be limited and likely to keep within the buffer even without the fix.

pcre2test: avoid overreading subject buffer with leading spaces

---

README
src/pcre2_fuzzsupport.c

These are a few very minor fixes/clarifications that came up when building 16- and 32-bit support with the fuzzer.

Minor fuzzer tidying

---

ChangeLog
doc/pcre2_jit_compile.3
doc/pcre2jit.3
src/pcre2.h.in
src/pcre2_error.c
src/pcre2_jit_compile.c
src/pcre2test.c
testdata/testoutput17

Added a new jit error code and tried to document it. The rest of the files are auto-generated, am I right?

Add error code for unsupported jit features

---

ChangeLog
src/pcre2_compile.c
src/pcre2_dfa_match.c
src/pcre2_internal.h
src/pcre2_jit_compile.c
src/pcre2_match.c
src/pcre2_printint.c
src/pcre2_study.c
testdata/testinput2
testdata/testinput6
testdata/testoutput2
testdata/testoutput6

This patch contains the core code of a new experimental feature called scan substring. It allows anchored matching the content of a capture group to a subpattern.
The parser (compiler) and interpreter is updated to support it. Dfa interpreter will not support it. JIT will support it in the future. Documenation is missing, I hope @PhilipHazel can help me with that. Several tests were added.

Support a new experimental feature called scan substring

---

src/pcre2.h.generic
src/pcre2.h.in

For all other error codes returned by pcre2_compile(), there are constants defined in pcre2.h which describe the error. Add the missing constants for the last two error codes.

Add missing constants for ERR100 and ERR101 in pcre.h

---

src/pcre2_jit_compile.c
src/pcre2_match.c
testdata/testinput2
testdata/testoutput2

I tried to figure out how to fix the bugs in the interpreter. Unfortunately the F,N,P, Flast_group_offset variables are a bit confusing for me, but at least the tests pass. I am thinking about whether keeping the current F instead of another RMATCH is a better idea. I am not even sure it is possible to do that.

Fix backtracking bugs in scan_substring

---

src/pcre2_study.c
testdata/testoutput2

The 'first code unit' (`firstcu`) optimization is more effective than the 'required code unit' (`reqcu`) optimization, since while `reqcu` can sometimes cause a non-matching subject string to be quickly rejected, `firstcu` can do the same thing _and_ help the regex engine to quickly skip forward to the best position to start matching from.
Hence, in `pcre2_study()`, when there is a conflict between enabling the `firstcu` and `reqcu` optimizations, it is better to choose `firstcu`.

Set 'first code unit' using 'starting code units' bitmap even when 'required code unit' is same

---

doc/html/pcre2test.html
doc/pcre2test.1
doc/pcre2test.txt

The 'expand' modifier is mentioned in later sections of the manpage, but is not included in any of the lists of possible modifiers.

Add missing 'expand' modifier to list in pcre2test manpage

---

src/pcre2_compile.c
src/pcre2_jit_compile.c
src/pcre2_match.c
testdata/testinput2
testdata/testoutput2

The idea is extending the scan substring argument to a list of capture group references. The brackets are scanned in definition order, and the first bracket in the list, which value is set is used for the substring scanning.
Unfortunately the implementation required code reorganizations, which made the patch more complex than it should be.

Support multiple group references for scan substring

---

src/pcre2_compile.c

When testing the new pattern rewriting phase for regex compilation using a fuzzer, I had a scary experience. Due to a bug in my pattern rewriting code, pcre2_compile() could return a totally invalid erroroffset. If a library user tried to do something with the erroroffset without checking it for validity, in the worst case, this had the potential to lead to an RCE vulnerability.
In case something similar ever happens again, I've added an assertion which will make it easier to notice the problem.

Use assertion to ensure erroroffset return from pcre2_compile is valid

---

.github/workflows/dev.yml
src/pcre2_internal.h

Make sure that any unexpected problem is reported as a job failure to improve visibility.
Looking at the log output is still encouraged until all exceptions are cleared

ci: make clang dev job failures fatal

---

src/pcre2_compile.c
testdata/testoutput15

While fuzzing PCRE2, I found a case in which `pcre2_compile` may incorrectly read past the end of the pattern string which it is given. Here are the details:
Patterns passed to `pcre2_compile` are not guaranteed to be null-terminated. Also, it can happen that there is an invalid pattern like this:
```
(*LIMIT_HEAP=123
```
If the next byte of memory after the end of the pattern happens to be a digit, it will be parsed as part of the limit value. Or, if the next byte is a right parenthesis character, it will be taken as the end of the `(*LIMIT_HEAP=nnn)` construct.
This will result in `skipatstart` being larger than `patlen`, which will result in underflow and an erroneous call to malloc requesting a huge number of bytes.

Guard against out-of-bounds memory access when parsing LIMIT_HEAP et al

---

CMakeLists.txt
config-cmake.h.in
configure.ac
src/config.h.generic
src/config.h.in
src/pcre2_convert.c
src/pcre2_util.h

Carlo pointed out that my code in a different PR was causing compiler warnings on Windows. The root cause is that `PCRE2_UNREACHABLE()` was not implemented on Windows.
Have I missed any other files which need to be updated?

Implement PCRE2_UNREACHABLE assertion for MS Visual C++

---

src/pcre2test.c

I believe that this will silence one warning when pcre2test is compiled with MS Visual C++. (However, I will double-check in the build for this PR to ensure that the warning is gone.)
The warning points out that there is a possible loss of precision when assigning a `size_t` value to a `uint16_t` variable. However, it is hard to imagine that the total number of "newline" characters recognized when performing a regex match will overflow a 16-bit unsigned int.

Silence one warning in pcre2test code (when compiled with Visual C++)

---

.github/workflows/dev.yml
RunTest.bat

The comments in RunTest.bat state that @zherczeg added 16-bit and 32-bit support... could he confirm that 544dfb00 reflects his intentions correctly?
I was able to run the CI jobs in my forked repo and the Windows 32-bit job passed. I guess that's a good thing... though since I have never seen it fail, I don't really know for sure that it is testing anything 😅

Updates to Windows tests (RunTest.bat)

---

src/pcre2_substitute.c
testdata/testinput2
testdata/testoutput2

This is a feature in Perl, which combines the functionality of the replacement casing operators:
```perl
$thevar = "Hello";
$thevar =~ s/(Hello)/>\l\U${1}</g;
print $thevar
```
PCRE2 should support this, for Perl compatibility.

Add Perl titlecasing

---

src/pcre2_compile.c
src/pcre2_error.c
testdata/testinput1
testdata/testinput2
testdata/testoutput1
testdata/testoutput2
testdata/testoutput5

Why mess around with something that's broken, and which no users are likely to want?
Grasp the nettle, and simply disallow `\x` with no following hex digits (following non-hex character, or at end of pattern).
As documented in the code comments added, this diverges from Perl's default behaviour, but aligns with Perl+warnings, so is consistent with best-practices Perl usage.

Add fix and tests for \x with no hex digits

---

src/pcre2_compile.c
src/pcre2_internal.h
src/pcre2_substitute.c
testdata/testinput2
testdata/testoutput2

Previously, using `\1` inside a pcre2_substitute string would cause a bad-replacement error.
Now, we support this syntax in the same way as Python, to mean the same as `${1}`.

Add Python-style \1 backreferences in pcre2_substitute()

---

src/pcre2_compile.c
testdata/testinput1
testdata/testoutput1
testdata/testoutput2

For backreferences of the form `\8000000` (larger than GROUP_MAX but smaller than INT_MAX) the regex was rejected as invalid, due to an out-of-range backreference.
However, for those of the form `\80000000000` (larger than INT_MAX) it would treat it as a escape for the literal character '8', which is inconsistent with Perl (confirmed by test).
This appears to be just an oversight in the code, and there's no test case so this condition wasn't covered.

Add test and fix for too-large octals starting with \8 or \9

---

src/pcre2_compile.c
src/pcre2_substitute.c
testdata/testinput2
testdata/testinput5
testdata/testoutput2
testdata/testoutput5

* Capture group names can be up to 128 characters, but `pcre2_substitute()` was only allowing 32-character names
* With `/utf`, capture group names can contain non-ASCII characters, but `pcre2_substitute()` was allowing ASCII names only
The new function `read_name()` takes a silly number of lines of code given what it does, but I wanted it to match visually as closely as possible with the corresponding function in `pcre2_compile.c`.
Note that we don't allow SPACE and HT inside `${name}` replacements, even though Perl does. I have kept this unchanged. I have no opinion or desire to add more whitespace skipping.

Fix pcre2_substitute() to allow all named captures to be referenced

---

src/pcre2_substitute.c
testdata/testinput2
testdata/testoutput2

This has minor security implications.
`pcre2_substitute()` calls `check_escape()` which returns a _positive_ compile-error. Unfortunately, this is returned back to the `pcre2_substitute()` caller, which interprets a non-negative code as meaning "substitute succeeded".
This could cause the client to process the return string, assuming that it is null-terminated, and perform an out-of-bounds read.
Clients which use the `*blength` parameter to determine the length of the returned string are unaffected.
The `pcre2test` application was itself affected: it would print garbage memory because it relies on the null terminator when `pcre2_substitute()` returns non-negative.

[Could cause OOB read in clients] Fix incorrect positive error code from pcre2_substitute()

---

maint/GenerateUcd.py
src/pcre2_compile.c
src/pcre2_internal.h
src/pcre2_ucd.c

Currently when utf caseless matching is requested, each character in a class range is checked one-by-one to find their other cases. I always thought this is inefficient, even if it is only done by the parser.
To speed things up, I have added a data structure, which contains ranges where characters have no other cases. The ranges have a minimum size. The size in uint32_t units with different minimum sizes (the number of ranges is half of that size):
```
minimum size 4: 124; /* 1111114 characters */
minimum size 8: 74; /* 1110983 characters */
minimum size 16: 60; /* 1110911 characters */
```
I choose 8 at the end, because only 74 values are needed, and these ranges cover 1110983 characters, which is 99.7% of all utf characters.
Performance improvement by the patch:
Original (-O3):
``` …
```

Improve caseless character range processing when utf is enabled

---

src/pcre2_compile.c
src/pcre2_substitute.c
testdata/testinput2
testdata/testoutput2

These are the standard syntaxes in Python and JavaScript for capture group references.
Python's `\g<name_or_num>` permits either a capture group name or number. We don't allow whitespace inside the `<>` nor do we allow `\g<*MARK>` syntax.
JavaScript's `$<name>` syntax only allows a capture group name; otherwise it's the same as `\g<name>`.

Add implementation of \g<...> and $<...> in substitute

---

.github/workflows/dev.yml
src/pcre2_compile.c
src/pcre2test.c

This job should at least ensure the library builds cleanly (although without JIT) and creates a DLL.
Its not as verbose as the original MSVC job (which has been renamed so it is clear it is 32bit) so that any warnings are clearly visible if building `pcre2grep`, `pcre2test` or JIT is enabled.

ci: add very basic 64bit Windows DEV job

---

src/pcre2_compile.c
testdata/testinput5
testdata/testoutput2
testdata/testoutput5

A "fixup" to the bug addressed by #472, and that corrects a small regression introduced there
where group numbers larger than 65535 will report and even less accurate erroroffset.

pcre2_compile: make erroroffsets returned from read_number() more accurate

---

src/pcre2.h.generic
src/pcre2.h.in
src/pcre2_compile.c
src/pcre2test.c
testdata/testinput10
testdata/testinput2
testdata/testinput5
testdata/testoutput10
testdata/testoutput2
testdata/testoutput5

PCRE2 follows Perl's rules for disambiguating octals:
* `\0` or `\0x` or `\0xx` are always octals
* `\1` to `\9` are always backrefs, as are `\8x` or `\9x`
* Other values, which lead with a non-zero octal digit, are interpreted based on how many capture groups are defined elsewhere in the regex
I have added here `PCRE2_EXTRA_NO_AMBIG_BSOCT` to allow following Python's saner rules. These might be a better choice for new applications without backwards compatibility concerns. Basically, with Python you only get octals if you really ask for them. An octal escape has to have either a leading zero (`\0 or \0x or \0xx`, or three octal digits `\xxx`). The ambiguous cases such as `\12` are always backreferences. The disambiguation is unaffected by how many patterns are defined elsewhere.
This …

Add a compile flag for Python-style octal disambiguation

---

doc/html/pcre2_set_optimize.html
doc/html/pcre2api.html
doc/html/pcre2pattern.html
doc/html/pcre2test.html
doc/index.html.src
doc/pcre2.txt
doc/pcre2_set_optimize.3
doc/pcre2api.3
doc/pcre2pattern.3
doc/pcre2test.1
doc/pcre2test.txt
src/pcre2.h.generic
src/pcre2.h.in
src/pcre2_compile.c
src/pcre2_context.c
src/pcre2_dfa_match.c
src/pcre2_internal.h
src/pcre2_intmodedep.h
src/pcre2_jit_compile.c
src/pcre2_match.c
src/pcre2test.c
testdata/testinput2
testdata/testoutput15
testdata/testoutput2
testdata/testoutput5
testdata/testoutput6

It is anticipated that over time, more and more optimizations will be added to PCRE2, and we want to be able to switch optimizations off/on, both for testing purposes and to be able to work around bugs in a released library version.
The number of free bits left in the compile options word is very small. Hence, we will start putting all optimization enable/disable flags in a separate word. To switch these off/on, the new API function pcre2_set_optimization() will be used.
The values which can be passed to pcre2_set_optimization() are different from the internal flag bit values. The values accepted by pcre2_set_optimization() are contiguous integers, so there is no danger of ever running out of them. This means in the future, the internal representation can be changed at any time without …

Add new API function pcre2_set_optimization() for controlling enabled optimizations

---

CMakeLists.txt
config-cmake.h.in
configure.ac
src/config.h.generic
src/config.h.in
src/pcre2_util.h
vms/configure.com

Simplify PCRE2_ASSERT() and while at it remove no longer needed dependency on __builtin_expect()
Fixes: #484

Do not use __builtin_unreachable() in PCRE2_ASSERT()

---

doc/pcre2_set_optimize.3
doc/pcre2api.3

Align it better to the style used in other similar pages (ex: pcre2_set_compile_extra_options.3) by including
enough information so it can be used independently of other pages.

improve usability of pcre2_set_optimize() documentation

---

ChangeLog
doc/pcre2syntax.3
src/pcre2_compile.c
testdata/testinput2
testdata/testoutput2

Complete the bugfix merged with #463 and update documentation (including ChangeLog)
The documentation itself might need further tweaks to better clarify when parsing of the
affected `pso` VERBs is meant to happen though.

pcre2_compile: avoid 1 byte buffer overread parsing VERBs

---

HACKING
src/pcre2_compile.c
src/pcre2_compile.h
src/pcre2_compile_class.c
src/pcre2_intmodedep.h
src/pcre2_jit_compile.c
src/pcre2_xclass.c
testdata/testinput5
testdata/testoutput5

The new method for processing ranges allows some optimizations in the code, e.g. the xclass processing can return early. Furthermore, the data-set created for each range is cached, and during the second pass of byte code generation the cache is used.

Implement pre-processed character range list caching

---

src/pcre2_substitute.c
testdata/testinput2
testdata/testoutput2

The `$&` replacement, and `` $` `` and `$'` are common sequences for `$0`, and "left of $0" / "right of $0" respectively. Perl supports these, so PCRE2 surely should.
The `$_` is less common but supported by some engines.
---
Finally, very very minor:
The `\b` escape is supported by Perl, so we should add it too.
The `\v` escape is there for completeness - it's not apparently supported by Perl, but many other dialects such as JavaScript or .NET use this C-inspired escape sequence for "vertical tab". It's obviously not possible to support this in patterns, but in the replacement string I can't see a reason not support it.

Substitute: add support for $& $` $' $_ and \b \v

---

src/pcre2_convert.c

Correct recent code changes that could have resulted in ABI problems by no longer returning the expected error code on fatal failure.
Since this assertion shouldn't had triggered unless a bug is introduced, it should be also safe to remove, but is likely to be added back once safe to do so.

pcre2_convert: fix unsafe use of PCRE2 assertions in API entrypoint

---

doc/pcre2compat.3
doc/pcre2pattern.3
src/pcre2_compile.c

Hopefully more clear on what "strict" refers to, in the context of hexadecimal escape codes

doc: fix silly confusion about re "strict" in recent changes

---

.github/workflows/dev.yml
maint/README
maint/utf8.c
src/pcre2_compile.c
src/pcre2_fuzzsupport.c
src/pcre2_match.c
src/pcre2_substitute.c
src/pcre2test.c

Make sure that no undesired integer wraparounds happen in the code, and that it is clear from other common issues.
It includes a "fix" in `pcre2_match.c` that could be handled better by the sanitizer and could be considered
a "false positive", and that future versions of the compiler would be able to avoid by using (the yet not released) `-fsanitize-undefined-ignore-overflow-pattern=unsigned-post-decr-while` option.

ci: add a full clang integer sanitizer DEV job

---

src/pcre2_substitute.c
testdata/testinput2
testdata/testoutput2

* `pcre2_substitute()` is not following the documentation's recommended practice for handling MARK names with embedded NULs.
* The CRLF-handling code assumes that, if newline_convention is not CR or LF, then CRLF is a valid newline. Presumably, this was true once upon a time, but now PCRE2_NEWLINE_NUL has been added. Corrected this minuscule error.

Fix two small issues with substitution nulls

---

src/pcre2.h.generic

Hi everyone,
I noticed that the `PCRE2_EXTRA_NEVER_CALLOUT` flag is missing from pcre2.h.generic. This omission causes errors when using the latest master branch (currently https://github.com/PCRE2Project/pcre2/commit/8c84b4ba5865c1b46313c5cf6325dd28ffc3888a) in my Zig project. Here are the errors I encountered:
```
error: use of undeclared identifier 'PCRE2_EXTRA_NEVER_CALLOUT'
if ((xoptions & PCRE2_EXTRA_NEVER_CALLOUT) != 0)
^
error: use of undeclared identifier 'PCRE2_EXTRA_NEVER_CALLOUT'
(ccontext->extra_options & ~PUBLIC_COMPILE_EXTRA_OPTIONS) != 0)
^
note: expanded from macro 'PUBLIC_COMPILE_EXTRA_OPTIONS'
PCRE2_EXTRA_NEVER_CALLOUT)
```
After adding `PCRE2_EXTRA_NEVER_CALLOUT` (copy from pcre2.h.in) to pcre2.h.generic, these errors were resolved.
Does this look good to you? Feel …

Add PCRE2_EXTRA_NEVER_CALLOUT flag to pcre2.h.generic

---

Makefile.am
doc/html/index.html
doc/html/pcre2_set_substitute_case_callout.html
doc/html/pcre2api.html
doc/html/pcre2compat.html
doc/html/pcre2pattern.html
doc/html/pcre2test.html
doc/index.html.src
doc/pcre2_set_substitute_case_callout.3
doc/pcre2api.3
doc/pcre2test.1
src/pcre2.h.in
src/pcre2_context.c
src/pcre2_intmodedep.h
src/pcre2_substitute.c
src/pcre2test.c
testdata/testinput2
testdata/testoutput2

This arises from the discussion we had a few weeks ago on the Excel call.
We discussed improving the case-handling of the pcre2_substitute function, but in general, Philip seemed not overly-enthusiastic, simply because correct locale-aware handling of user-visible strings is _hard_.
I agree. This PR adds a callout (callback) function to allow a third-party Unicode engine to be used for user-visible string processing. This can be used by applications to do locale-aware case transformations.
It's still a one-char-to-one-char mapping, which is simplistic, but allows support for more locales than the current system.
Aside: PCRE2's current Unicode handling for pattern matching (using CaseFolding.txt data) is really rather good. This should not be locale-aware, since case-equivalence of …

Add substitute case callout function

---

HACKING
src/pcre2_compile.c
src/pcre2_internal.h
src/pcre2_jit_compile.c
src/pcre2_match.c
src/pcre2_printint.c
src/pcre2_study.c
testdata/testinput5
testdata/testoutput5

When you introduced caseless_restrict earlier in the year, it looks like you forgot to add it to the `OP_REFI` (and `OP_DNREFI`) comparison.
It's actually a bit tricky to add, because it seems the "flags" that are tracked during compile are not written out to the bytecode.
So, I added one extra field to `OP_REFI` to record the caseless flag. (Currently, it's just "caseless_restrict", but as I mentioned, I'll be adding "turkish_casing" in a future PR.)
I _think_ there's no other way to do it? I hope the flags aren't stored in the bytecode already and I just missed it.
It seems a bit wasteful, perhaps, to spend a uint8 (or uint32 in the case of the 32-bit library), but I think you basically forced this outcome back when you added the `(?r)` flag allowing caseless_restrict to be varied …

Fix OP_REFI for caseless_restrict

---

doc/pcre2test.1
perltest.sh
src/pcre2_compile.c
src/pcre2test.c
testdata/testinput11
testdata/testinput4
testdata/testinput9
testdata/testoutput10
testdata/testoutput11-16
testdata/testoutput11-32
testdata/testoutput12-16
testdata/testoutput14-16
testdata/testoutput4
testdata/testoutput9

As a solution that could be used to avoid the ambiguous syntax of the other escape sequences supported by pcre2test, add `\N{U+hh...}`
Includes bugfixes to the handling of `\o{dd...}` and hopefully improved documentation and tests.

pcre2test: add support for \N{U+hh...} escapes in subject

---

doc/pcre2test.1
perltest.sh
src/pcre2_compile.c
src/pcre2test.c
testdata/testinput1
testdata/testinput11
testdata/testinput4
testdata/testinput9
testdata/testoutput1
testdata/testoutput11-16
testdata/testoutput11-32
testdata/testoutput4
testdata/testoutput9

First patch is really a fixup for #528 with the second patch being the real meat.
Posted separately so it is easier to see the independent changes, but will squash them otherwise.

perltest: add support for hex modifier

---

perltest.sh
src/pcre2test.c
testdata/testinput1
testdata/testinput3
testdata/testoutput1
testdata/testoutput3
testdata/testoutput3A
testdata/testoutput3B
testdata/wintestinput3
testdata/wintestoutput3

Make comparing behaviour between Perl and PCRE2 easier when locale is involved (almost making test3 Perl compatible), plus cleaning test3 so it is again working on Windows as well as other fixes.

perltest: add support for locale modifier

---

RunTest
doc/pcre2syntax.3
src/pcre2_jit_compile.c

Additional code would be generated when framesize == 0 that would be dangerous so exempt it and add an assert to catch any situations that could trigger it in the future.

pcre2_jit_compile: avoid potential wraparound if framesize == 0

---

src/pcre2_util.h

Using assert rather than abort will give a (very slightly) better error message, which includes the containing function name.
Only affects Debug builds.

Use assert() for unreachable assertions

---

src/pcre2_compile.c
src/pcre2_compile.h
src/pcre2_compile_class.c
src/pcre2_intmodedep.h

I think the new code is quite nice and works nicely. I did some code reworks to improve the operations. There is no byte code optimizations. @NWilson please check.

Various code improvements for eclasses

---

testdata/testinput4
testdata/testoutput4

PCRE2's behaviour matches Perl currently, and Python's regex module (the standard re module doesn't have \P{...}).
However, JavaScript behaviour changed recently (when they added the new 'v' flag; the old 'u' flag's behaviour is unchanged), so this case is worth additional testing.
Raised in issue #497.

Add additional tests for negated /[^\P{Lu}]/i behaviour

---

ChangeLog
src/pcre2_jit_compile.c
src/pcre2_jit_test.c

The tricky part is that newlines can be two character long, and can start at the middle of \r\n.
I also accidentally found an old bug and fixed it. It requires a somewhat complicated pattern.

Improve repeated matching of newlines

---

.github/workflows/dev.yml
src/pcre2_auto_possess.c
src/pcre2_compile.c
src/pcre2_study.c

The CI configuration was using `CC='gcc -O0`. However, this doesn't work! Because CFLAGS was unset, `./configure` would set CFLAGS to `-O2`, resulting in a commandline of `gcc -O0 ... -O2 ...`.
Fixing this reveals that GCC generates additional warnings when in `-O0` mode. Presumably it doesn't do dead-code pruning, and so generates additional areas in provable-unreachable sections of code (which would be pruned in `-O2`).

Fix the -O0 configuration and its warnings

---

src/pcre2_jit_compile.c
src/pcre2_jit_test.c

The algorithm is rewritten. It should cover more cases and non-recursive.
Testing is difficult though. When it covers cases that it should not, the matching should fail, so that can be tested at some level. However, the opposite, when it does not cover cases, that it should, the effect is just slower matching.
Fixes #558 since it is non-recursive.

Non-recursive scan prefix in JIT

---

ChangeLog
src/pcre2_jit_compile.c
src/pcre2_jit_test.c

Not a trivial patch, fuzzing will be useful. Fixes a bug in caseful matching as well.

Remove fixed locals for iterators

---

src/pcre2_auto_possess.c
src/pcre2_compile.c

Remove dead code for handling quantifier after OP_FAIL

---

.github/workflows/build.yml

Add coverage job

---

.github/workflows/dev.yml
src/pcre2_compile_class.c
src/pcre2_substitute.c

In the `maint` directory, Philip says he checks the CMake Unity build before doing a release.
I gave it a go... and it's been broken by recent changes (file-static functions with colliding names: `read_name` and `optimize_class`).

Add CI job and fix for CMake Unity build

---

src/pcre2_jit_compile.c
src/pcre2_jit_simd_inc.h

Testing on some non-x86 cpus could be added to CI at some point (ARM, x390x)

JIT compiler update

---

src/pcre2_compile.c
src/pcre2_match.c
testdata/testinput2
testdata/testinput21
testdata/testinput23
testdata/testoutput2
testdata/testoutput21
testdata/testoutput23

One switch case in pcre2_compile.c is not covered by any tests (the ERR7 default).
Add tests covering all the possible escapes, and fix a couple that weren't working (ESC_k and ESC_ub).
Also fix some empty statements causing coverage failures in pcre2_match.c.

Improve coverage of escapes in character classes

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/cifuzz.yml
.github/workflows/clang-analyzer.yml
.github/workflows/codeql.yml
.github/workflows/dev.yml
.github/workflows/scorecards.yml

* Use hashes to pin versions of third-party Actions used in CI
* Use GitHub's dependabot to do a monthly update of the Actions
* Restrict all Workflows to use a read-only token (except for the steps which need to upload a SARIF file)

Apply some security hardening, as recommended by OSSF scorecard

---

.github/workflows/build.yml
.github/workflows/cifuzz.yml
.github/workflows/clang-analyzer.yml
.github/workflows/codeql.yml
.github/workflows/dev.yml
.github/workflows/scorecards.yml

* Adding `workflow_dispatch` to all workflows lets us manually trigger them if needed
* Added `releases/` branch for creating signed tags for future releases
* Updated Scorecard configuration after V2 update

Update scorecard-V2 PAT, and tweak workflow triggers

---

src/pcre2_jit_char_inc.h
src/pcre2_jit_compile.c

This is just one line change, but I want to make sure it does not break anything.

Change READ_CHAR_MAX to maximum unsigned value

---

src/pcre2_compile.c
src/pcre2_compile_class.c
src/pcre2_dfa_match.c
src/pcre2grep.c
src/pcre2posix.c

One of these appears in Coverity's dashboard; the rest are from clang-scan.
See #576

Suppress some minor analysis warnings

---

doc/html/pcre2api.html
doc/pcre2.txt
doc/pcre2api.3
src/pcre2_substitute.c
src/pcre2test.c
testdata/testinput2
testdata/testoutput2

Avoid one crash introduced with recent changes to substitute code as well as clarify what the expected offset value should be when overflowing the provided buffer.

Fix null-dereference bug in pcre2_substitute

---

.github/workflows/build.yml

These are only run after a PR is merged, not every time you push to a PR.
They use a third-party GitHub Action that starts up a VM using Qemu.
The Solaris one is cheating a little - I'm using GCC rather than Oracle Developer Studio's `cc` compiler, because that's a real pain to install. On the other hand, most people probably use GCC on Solaris now anyway, so maybe it is a fair test of whether our Solaris support is OK.

Add Solaris and FreeBSD to our CI

---

.github/workflows/build.yml

This will help us with issue #601 
I don't know how good the Codecov.io service is. Let's just give it a go, and see if it helps us at all.
In theory, it should be able to tell us how well-covered by tests our code is, specific to each PR.

Add Codecov.io integration

---

.bazelrc
.github/workflows/dev.yml
.gitignore
BUILD.bazel
MODULE.bazel
RunTest.bat

I know absolutely no Bazel!
The existing Bazel build isn't implementing any of the Autoconf/CMake at all - not testing for header files, or setting any of the platform-specific macros.
That seems... less than ideal. But anyway, if users really want to use Bazel, then can do so. But perhaps the Bazel file should instead shell out to a "proper" build system like CMake, if that's what is required for actually performing system-specific configuration?
I have attempted to update the Bazel file the minimal amount that enables us to at least run the unit tests, and confirm that the build was successful.

Add Bazel build to CI

---

doc/html/pcre2api.html
doc/pcre2.txt
doc/pcre2api.3
src/pcre2_substitute.c
testdata/testinput2
testdata/testoutput2

I reckon that callers are assuming that when you use the PCRE2_SUBSTITUTE_OVERFLOW_LENGTH option, it will calculate the entire memory requirement in one go. Just two calls should be sufficient (rather than needing to loop with a gradually-increasing buffer size).
However, with a substitution callout this is not true. If you call once with PCRE2_SUBSTITUTE_OVERFLOW_LENGTH, the buffer length returned might still not be sufficient for the second call to succeed.
This is because the callout might not be called the first time, but the second time it will be called and can affect control flow, by requiring even more buffer to be used. This occurs even if the callout is completely stateless, idempotent and well-behaved.
This fix ensures that when we skip a callout (due to overflow), we still …

Small improvement to combination of substitution callout + overflow

---

maint/PrepareRelease
maint/UpdateCommon.py
maint/UpdateDates.py
maint/UpdateRelease.py

The workflow shall be:
* When the release number is bumped, all references to that release number need to be bumped immediately. (For example, when the source code moves from 10.45 → 10.46, the man pages must do so as well.)
* When documentation is updated, there's no need to update the "last modified" dates by hand. We can sweep those all up during the release process. Or update them immediately - there's no harm in it; we simply aren't obliged to.

Add maint scripts for checking and updating library version & updated dates

---

src/pcre2_jit_compile.c
testdata/testinput1
testdata/testinput4
testdata/testoutput1
testdata/testoutput4

This should be the last patch of this work. All `[class]{a,b}+/?/nothing` now compiles `[class]` once. In the past a `[class]+` may compiled three times, which consumed a large space for some eclasses.

Improve non-greedy repeat support

---

src/pcre2_jit_compile.c

I realized there is a case (charpos + fast fail), which is easy to break. The new code makes it harder to break. Also reduces the memory consumption of the compiler a bit.

Improve iterator backtrack handling

---

src/pcre2_compile.c
src/pcre2_compile_class.c
src/pcre2_jit_char_inc.h
testdata/testinput4
testdata/testinput5
testdata/testoutput4
testdata/testoutput5

Minor code movement. The code runs once per pattern in its new place.

Move L& conversion

---

src/pcre2_jit_compile.c

Congrats on the RC1 🙂 
I've got the following warning when trying to compile it with MSVC though, which is a problem when you turn warning as errors on:
> Warning C4018 : '>': signed/unsigned mismatch
(I supposed the PR should target the master branch)

Fix warning about signed/unsigned mismatch

---

.github/workflows/dev.yml
CMakeLists.txt
RunTest
src/pcre2grep.c
testdata/testoutput3C

Also fix a few minor portability issues.
- The unix "MSYS" environment has an usual (but sane) French locale, requiring a test update
- pcre2grep needs a fix to use the WIN32 when both WIN32 and sys/stat.h are available
Fixes #127

Add CI for MSYS2

---

doc/pcre2grep.1
maint/132html
maint/CheckMan
maint/PrepareRelease

Debian's "lintian" picked this up - line 950 in the man page starts with a `'` which is how you start a roff request. You can reproduce the warning thus:
```
LC_ALL=C.UTF-8 MANROFFSEQ='' MANWIDTH=80 \
man --warnings -E UTF-8 -l -Tutf8 -Z doc/pcre2grep.1 >/dev/null
```
The fix is to add a zero-width space (`\&`) to the start of the relevant line (indeed `groff_man(7)` suggests exactly this use for `\&`).
This is obviously not a critical issue, but it'd be nice if it made it into 10.45 please :)

pcre2grep.1 - fix warning about undefined macro 0

---

src/pcre2_jit_neon_inc.h
src/pcre2grep.c
src/pcre2test.c

This addresses Aaron's (ucko's) complaint from #655.

Fix some Clang warnings with `-Wshorten-64-to-32`

---

LICENCE.md
Makefile.am
maint/manifest-tarball
src/pcre2_fuzzsupport.c
src/pcre2posix_test.c

Also, add missing license header to two files in the repo.
Fixes #686

Add LICENSE file for sljit in the tarball

---

.gitignore
Makefile.am
README
RunTest
doc/html/README.txt
maint/RunPerlTest

This makes it easier to see all the failures at once, rather than having to fix one at a time. The output is now grouped into directories.

Improve RunTest to continue after a test failure

---

src/pcre2_compile.c
src/pcre2_compile.h

The new code only do the searches once.
Also rename META_SCS_NAME and META_SCS_NUMBER to META_CAPTURE_NAME and META_CAPTURE_NUMBER respectively, since these are not depend on scan substring.

Optimize capture name compilation

---

doc/html/pcre2-config.html
doc/html/pcre2.html
doc/html/pcre2api.html
doc/html/pcre2matching.html
doc/html/pcre2pattern.html
doc/html/pcre2sample.html
doc/html/pcre2syntax.html
doc/html/pcre2test.html
doc/pcre2-config.1
doc/pcre2-config.txt
doc/pcre2.3
doc/pcre2.txt
doc/pcre2api.3
doc/pcre2matching.3
doc/pcre2pattern.3
doc/pcre2sample.3
doc/pcre2syntax.3
doc/pcre2test.1
doc/pcre2test.txt

Another batch of very small typos & issues

---

.github/workflows/dev.yml

The `ubuntu-20.04` GitHub runner will be discontinued in around a month.
We can still test on this OS, by running these jobs in a container.

Run build on deprecated Ubuntu 20.04 in a container

---

src/pcre2_compile.c
src/pcre2_compile.h
src/pcre2_compile_cgroup.c
testdata/testinput2
testdata/testoutput2

This patch optimizes the argument list of scan substring by removing duplications. Multinames are only removed if all corresponding captures are removed as well.
Not a simple patch unfortunately.
It would not be bad, if equality here could be checked somehow:
https://github.com/PCRE2Project/pcre2/blob/master/src/pcre2_compile.c#L10854
The greater case is only needed for a few patterns. Don't know how to do this. Maybe tests should contain a `#` option to enforce equality, and that could be disabled for specific patterns.

Remove duplicated scan substring captures

---

src/pcre2_jit_compile.c
src/pcre2_jit_test.c

Avoid saving the same capture twice. Furthermore use a bitset for optimized captures to reduce memory consumption.

Track recorded captures during frame construction

---

BUILD.bazel

This is important for e.g. glib/gio, which also
has an internal config.h, and fails to compile, as it often picks up the pcre2 config.h first.

Stop leaking internal headers to other libraries.

---

.github/workflows/dev.yml
build.zig

Followup to #722
* Fix Windows build warning by adding PCRE2_STATIC to pcre2test
* Remove unnecessary `.linkLibc()` command, now that we have `link_libc = true` in the Module declarations
* Update the old `std.Build.Step.Compile.create(...)` calls to the brand-new `b.addLibrary(...)` function. They added this exactly for our use-case, to allow dynamically selecting between `addStaticLibrary/addDynamicLibrary` variants.

A few further tweaks to Zig 0.14 support

---

src/pcre2_compile.c
src/pcre2_dfa_match.c
src/pcre2_match.c
src/pcre2_substitute.c

The value `""` is a `char[1]` array with a single zero byte. It should not be cast to a PCRE2_SPTR, which is a pointer to an array of 1/2/4-byte values. It may not even have the required pointer alignment for a PCRE2_SPTR (in 16 or 32 bit mode).
The pointer is never dereferenced anyway, since the length is zero.
Reported by Microsoft's OACR linter.
As a quick and easy fix, I'll just set it a non-null value with the shortest possible length (no zero-length arrays allowed in C).
This has the best chance of silencing linters that want us to have a non-NULL value for the zero-length pointer.

Fix some incompatible pointer casts

---

doc/html/pcre2api.html
doc/pcre2.txt
doc/pcre2api.3

Fixes #337
We won't implement more advanced/alternative global replacement strategies, but we can at least write a few sentences explaining how to do it in application code.

Add a little additional documentation on how to emulate pcre2_substitute's loop

---

doc/html/pcre2pattern.html
doc/html/pcre2syntax.html
doc/pcre2.txt
doc/pcre2pattern.3
doc/pcre2syntax.3
testdata/testinput2
testdata/testoutput2

It also appears that some of the syntax variants, such as `(?P>name(grouplist))` were not covered by tests, so I have added some extra examples to make sure.
To be honest, this is my first time using the feature, and I must say it's very nice.

Add documentation for subroutine return values

---

.github/workflows/build.yml
RunGrepTest
RunGrepTest.bat

It's not available on Windows, but we hadn't noticed this because it's provided by the Git for Windows tools which I have installed. This is not good practice to require these tools as a build dependency.
I have replaced "head -1" with "pcre2grep -m1 .*" which matches and prints the first line. For consistency, I have made the same change on Unix.
Fixes #741

Remove use of 'head' Unix tool in pcre2grep test

---

CMakeLists.txt

The problem is that the Readline/zlib include paths were being included before our own include path (wrong import order). This caused a problem if the zlib include path was /usr/local/include, and that directory happened to unfortunately contain a pcre2.h file for an (older) version of PCRE2.

Fix a build issue due to previous CMake change

---

libpcre2-16.pc.in
libpcre2-32.pc.in
libpcre2-8.pc.in
libpcre2-posix.pc.in

The pkg-config file has License variable that that sets the software license.
This sets 'BSD-3-Clause WITH PCRE2-exception' as defined in SPDX to License.
Ref: https://github.com/pkgconf/pkgconf/blob/master/man/pc.5#L116

Add License variable to pkg-config file

---

.editorconfig
Makefile.am

This fixes some annoyances for me. I need to insert tabs into the makefiles and spaces elsewhere; I don't want trailing whitespace to be stripped when I edit the test files; and I need to open testinput1 in Latin-1 and testinput2 in UTF-8 mode. All this can be automated.
The editorconfig file should work with any text editor - although note that VS Code needs an extension to make use of it.

Add a simple .editorconfig file

---

src/pcre2.h.generic
src/pcre2.h.in
src/pcre2_compile.c
src/pcre2_compile.h
src/pcre2_error.c
src/pcre2test.c
testdata/grepoutput
testdata/testinput10
testdata/testinput12
testdata/testinput2
testdata/testinput5
testdata/testoutput10
testdata/testoutput12-16
testdata/testoutput12-32
testdata/testoutput18
testdata/testoutput2
testdata/testoutput21
testdata/testoutput23
testdata/testoutput28
testdata/testoutput5

Changes to error offsets, fixing inconsistencies

---

doc/pcre2_match_data_create_from_pattern.3
src/pcre2_match_data.c

would allow something like:
```c
re = pcre2_compile(...);
can_jit = !pcre2_jit_compile(re, PCRE2_JIT_TEST_ALLOC);
md = pcre2_match_data_create_from_pattern(re, ...);
if (re != NULL && md != NULL) do {
/* do some work here, including matches and maybe even some on demand JIT compilation */
} while (!done_matching_or_replacing)
/* do some cleanup here, no need to check for NULL when calling the corresponding `_free()` functions */
```
which matches a similar construct that uses pcre2_match_data_create() instead.

pcre2_match_data: allow pcre2_match_data_create_from_pattern() with a NULL as the first parameter

---

build.zig

Allow getting a library with support for JIT (if supported by sljit, of course) and its corresponding `pcre2test`.
Note that zig doesn't care about `pcre2grep` so the corresponding `config.h` changes are not included.

build.zig: add option -DJIT to enable JIT

---

RunTest
RunTest.bat
doc/index.html.src
doc/pcre2_config.3
doc/pcre2api.3
src/pcre2.h.in
src/pcre2_config.c
src/pcre2test.c

`pcre2test` reports the `linksize` that was set at build time by all libraries, but at least in the case of the 32-bit library, it is never correct by default, or even relevant as described in [pcre2build](https://www.pcre.org/current/doc/html/pcre2build.html#SEC10).
CAVEAT: before this change; eventhough there were three (one per library, if all enabled) identical versions of this function linked with pcre2test, only the first one found was being used and that was "by design", which this changes.

pcre2_config: address inconsistency with the linksize reported in non 8-bit libraries

---

doc/html/pcre2pattern.html
doc/html/pcre2syntax.html
doc/pcre2.txt
doc/pcre2pattern.3
doc/pcre2syntax.3
src/pcre2_printint_inc.h
testdata/testinput2
testdata/testoutput2
testdata/testoutput5
testdata/testoutput8-16-2
testdata/testoutput8-16-4
testdata/testoutput8-32-4
testdata/testoutput8-8-2
testdata/testoutput8-8-3
testdata/testoutput8-8-4

Simplify the code and print all parameters

pcre2test: improve `binmode`

---

.github/workflows/build.yml
CMakeLists.txt
Makefile.am
README
cmake/PCRE2UseSystemExtensions.cmake
doc/html/README.txt
maint/manifest-tarball
src/pcre2_intmodedep.h
src/pcre2_study.c

- Added CMake on z/OS to CI builds
- Added CMake module to enable _ALL_SOURCE if required for getrlimit(). This was already being done by Autoconf.
- Excluded pcre2_grep_test on EBCDIC platforms.  This was already being done for Autoconf builds.
- Suppressed compiler warnings for UINT16_MAX. On most platforms it's the integer constant `65535` (a signed constant), but on z/OS and possibly AIX it's defined to `65535u` (an unsigned constant), which causes warnings about unexpected signedness in comparisons and arithmetic.
Fixes #764, hopefully

Add some CMake fixes for z/OS (not previously tested with CMake)

---

src/pcre2test.c

- A dangerous STRLEN macro was casting only part of its argument, which lead to unexpected behaviour in one instance (luckily harmless)
- A "compiler warning suppression" from a previous version of the code, which is definitely now obsolete.
- A belt-and-braces check which attempted to add a null terminator, but which was only writing a single byte. Thankfully no code actually reads the terminator anyway.

Fix three minor issues in pcre2test

---

src/pcre2_dfa_match.c
src/pcre2_match.c
src/pcre2test_inc.h

It's totally legal to return NULL for malloc(0), but every other platform that we target returns a non-NULL pointer. We don't need to do an allocation anyway (nor do we need to copy the terminating NUL byte).
This PR fixes a CI build failure on the z/OS runner.

Avoid zero-length allocations, which return NULL on z/OS
